export const sensors = [
  {
    id: 1,
    name: "Lodówka",
    value: 6,
    unit: "°C",
    lastSeen: new Date(),
    online: true,
  },
  {
    id: 2,
    name: "Balkon",
    value: 20,
    unit: "°C",
    lastSeen: new Date(),
    online: true,
  },
  {
    id: 3,
    name: "Pokój",
    value: 21.3,
    unit: "°C",
    lastSeen: new Date(),
    online: true,
  },
  {
    id: 4,
    name: "Wilgotność",
    value: 45,
    unit: "%",
    lastSeen: new Date(),
    online: true,
  },
  {
    id: 5,
    name: "Pobór mocy",
    value: 374.8,
    unit: "W",
    lastSeen: new Date(),
    online: true,
  },
];
